import fs from 'node:fs/promises';import path from 'node:path';import {build} from 'esbuild';import {portableFiles} from './portable-files.mjs';
import {fullHome,page,data,journal,article} from '../src/templates.mjs';
await fs.mkdir('dist/assets',{recursive:true});await fs.cp('public','dist',{recursive:true});await fs.copyFile('src/style.css','dist/assets/style.css');

await build({absWorkingDir:process.cwd(),tsconfigRaw:{compilerOptions:{}},entryPoints:[path.resolve('src/main.js'),path.resolve('src/sculpture.js')],plugins:[portableFiles],bundle:true,splitting:true,format:'esm',outdir:'dist/assets',minify:true,target:'es2022',entryNames:'[name]',chunkNames:'chunk-[hash]'});
const urls=[];async function write(url,options){const dir=path.join('dist',url);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'index.html'),page({...options,url}));urls.push(url)}
await write('/',{body:fullHome(),title:'Roseval Design — Agence web à Toulouse, création de sites & SEO',description:'Antonny Freval Ros, freelance à Toulouse. Création de sites internet dès 399 €, SEO local, identité visuelle et automatisation IA. Devis gratuit sous 24h.',schema:[{'@type':'FAQPage',mainEntity:data.faq.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))}]});
const breadcrumb=(name,url)=>({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Accueil',item:'https://rosevaldesign.com/'},{'@type':'ListItem',position:2,name,url:'https://rosevaldesign.com'+url,item:'https://rosevaldesign.com'+url}]});
await write('/blog',{body:journal(),title:'Journal — Conseils web, SEO & IA à Toulouse | Roseval Design',description:'Les articles d’Antonny Freval Ros : création de sites web, SEO local à Toulouse, design, budget et intelligence artificielle.',schema:[breadcrumb('Journal','/blog')]});
for(const p of data.posts){const url='/blog/'+p.slug;await write(url,{body:article(p),title:p.title+' | Roseval Design',description:p.excerpt,schema:[{'@type':'BlogPosting','@id':'https://rosevaldesign.com'+url,headline:p.title,description:p.excerpt,datePublished:p.date,author:{'@type':'Person','@id':'https://rosevaldesign.com/#antonny',name:'Antonny Freval Ros',url:'https://rosevaldesign.com/#about'},publisher:{'@id':'https://rosevaldesign.com/#organization'},image:new URL(p.image,'https://rosevaldesign.com').href,mainEntityOfPage:'https://rosevaldesign.com'+url,inLanguage:'fr-FR'}, {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Accueil',item:'https://rosevaldesign.com/'},{'@type':'ListItem',position:2,name:'Journal',item:'https://rosevaldesign.com/blog'},{'@type':'ListItem',position:3,name:p.title,item:'https://rosevaldesign.com'+url}]}]})}
const titles={'mentions-legales':'Mentions légales','politique-confidentialite':'Politique de confidentialité','politique-cookies':'Politique des cookies'};
for(const [slug,body]of Object.entries(data.legal)){await write('/'+slug,{body:'<article class="section wrap legal"><a class="back-link" href="/">← Retour au site</a>'+body+'</article>',title:titles[slug]+' | Roseval Design',description:titles[slug]+' de Roseval Design, studio de création web à Toulouse. Informations et contact : roseval.design@gmail.com.',schema:[breadcrumb(titles[slug],'/'+slug)]})}
await fs.writeFile('dist/404.html',page({body:'<section class="section wrap"><p class="eyebrow">404 / PAGE INTROUVABLE</p><h1 class="page-title">On a perdu<br>le fil.</h1><p>Cette page n’existe pas ou a été déplacée.</p><a class="button primary" href="/">Revenir au studio ↗</a></section>',title:'Page introuvable | Roseval Design',description:'Retrouvez le studio Roseval Design.',url:'/404',noindex:true}));
await fs.writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>'<url><loc>https://rosevaldesign.com'+u+'</loc></url>').join('')+'</urlset>');
await fs.writeFile('dist/robots.txt','User-agent: *\nAllow: /\n\nSitemap: https://rosevaldesign.com/sitemap.xml\n');
console.log('Build réussi : '+urls.length+' pages statiques, sitemap, robots.txt, 404 et animations 3D.');
