// Editorial details grounded in the existing portfolio and client testimonials.
export const caseStudies = [
  {slug:'fl-renovation',project:'FL Rénovation',title:'Site web et identité pour FL Rénovation | Roseval Design',description:'Découvrez le projet FL Rénovation : site vitrine, identité visuelle et présentation du savoir-faire d’une entreprise de rénovation à Toulouse.',need:'Présenter une entreprise de rénovation et rendre son image plus cohérente.',work:'Site vitrine, identité visuelle et présence numérique.',sections:[['Rendre le métier compréhensible','Pour une entreprise de rénovation, un site sert à expliquer les prestations et à montrer les réalisations avant la prise de contact. Ce projet associe le site vitrine et l’identité visuelle pour présenter l’entreprise dans un ensemble cohérent.'],['Relier le site à l’image de marque','Le retour de Laurent porte sur la refonte de son image de marque et la lisibilité de sa présentation. Le travail ne se limite donc pas à une page web : les choix graphiques doivent accompagner la manière dont l’entreprise se présente à ses clients.'],['Ce que vous pouvez préparer pour un projet similaire','Rassemblez vos principales prestations, des photos de chantiers que vous êtes autorisé à publier, votre zone d’intervention et les informations nécessaires à une demande de devis. Ces éléments permettent de définir les pages utiles avant de choisir les effets visuels.']]},
  {slug:'dpc-immobilier',project:'DPC Immobilier',title:'Site et identité de DPC Immobilier | Roseval Design',description:'Le projet DPC Immobilier par Roseval Design : plateforme de services immobiliers, logo et couleurs pour une présentation cohérente de l’activité.',need:'Présenter les services immobiliers avec une identité renouvelée.',work:'Plateforme de services immobiliers et identité visuelle.',sections:[['Présenter les services immobiliers','Une présence immobilière doit permettre au visiteur de comprendre l’activité et de trouver le bon interlocuteur. Le projet DPC Immobilier associe une plateforme de services et une identité visuelle renouvelée.'],['Un logo et des couleurs cohérents','David et Phaythoune mentionnent dans leur retour le nouveau logo, les nouvelles couleurs et l’accompagnement reçu. Ces éléments relient la présentation du site à l’identité de l’entreprise.'],['Préparer votre propre projet immobilier','Listez les services proposés, les publics concernés et les informations à présenter. Précisez ensuite les besoins de mise à jour et de prise de contact. Un catalogue d’annonces, un outil métier ou une intégration externe éventuelle doit être défini séparément dans le devis.']]},
  {slug:'ap-design',project:'AP Design',title:'Boutique en ligne et identité AP Design | Roseval Design',description:'Découvrez AP Design : une boutique en ligne, une identité numérique et des supports de communication réalisés avec Roseval Design.',need:'Développer une présence en ligne cohérente avec les supports de communication.',work:'Boutique en ligne, identité numérique et supports de communication.',sections:[['Relier la boutique et la marque','Le projet AP Design associe une boutique en ligne, l’identité numérique et des supports de communication. L’objectif de cet ensemble est de présenter la même entreprise de manière cohérente sur le web et sur ses supports.'],['Un accompagnement sur plusieurs supports','Dans son témoignage, Allen évoque l’image de marque, les cartes de visite et les conseils reçus. La réalisation illustre un besoin qui dépasse la seule mise en ligne d’un catalogue.'],['Préparer une boutique en ligne','Avant le devis, réunissez les produits ou prestations à présenter, vos photos, les variantes et les besoins de gestion. Définissez les modes de paiement, de livraison et de suivi souhaités : leur mise en place dépend du périmètre retenu.']]}
];

export async function buildCasePages(write,data,esc){
  const origin='https://rosevaldesign.com';
  const crumbs=(items)=>({'@type':'BreadcrumbList',itemListElement:items.map(([name,url],i)=>({'@type':'ListItem',position:i+1,name,item:origin+url}))});
  const cta='<div class="article-cta"><div><h2>Un projet pour votre entreprise ?</h2><p>Présentez votre activité, votre besoin et les contenus disponibles. Le périmètre et le budget sont définis au devis.</p></div><a class="button primary" href="/web#contact">Présenter mon projet ↗</a></div>';
  const cards=caseStudies.map((c,i)=>{const p=data.projects.find(p=>p.title===c.project);return `<article class="case-card"><a class="project" href="/realisations/${c.slug}"><div class="project-image"><img src="${p.image}" width="960" height="600" loading="lazy" alt="Aperçu du projet ${esc(c.project)}"><span class="project-open" aria-hidden="true">↗</span></div><div class="project-meta"><span>0${i+1} / ${esc(p.category)}</span><h2>${esc(c.project)}</h2></div></a><div class="case-copy"><p>${esc(c.work)}</p><a href="/realisations/${c.slug}">Découvrir le projet ↗</a></div></article>`}).join('');
  await write('/realisations',{title:'Réalisations : sites web et identités | Roseval Design',description:'Découvrez trois projets Roseval Design : FL Rénovation, DPC Immobilier et AP Design. Besoins, prestations et témoignages clients.',body:`<section class="section wrap"><p class="eyebrow">LES RÉALISATIONS DU STUDIO</p><h1 class="page-title">Des projets.<br><span>Des entreprises.</span></h1><p class="page-intro">Site vitrine, services immobiliers ou boutique en ligne : découvrez les besoins et les prestations de trois projets accompagnés par Roseval Design.</p><div class="case-grid">${cards}</div><p>Les aperçus présentent les projets du portfolio. Les sites clients peuvent évoluer après leur livraison.</p>${cta}<a class="back-link" href="/web#portfolio">Voir aussi les autres réalisations et expérimentations ↗</a></section>`,schema:[crumbs([['Accueil','/'],['Réalisations','/realisations']]),{'@type':'ItemList',itemListElement:caseStudies.map((c,i)=>({'@type':'ListItem',position:i+1,name:c.project,url:origin+'/realisations/'+c.slug}))}]});
  for(const [i,c] of caseStudies.entries()){
    const p=data.projects.find(p=>p.title===c.project),t=data.testimonials[i],url='/realisations/'+c.slug;
    await write(url,{title:c.title,description:c.description,body:`<article class="section wrap article"><a class="back-link" href="/realisations">← Toutes les réalisations</a><p class="eyebrow">${esc(p.category)}</p><h1 class="article-title">${esc(c.project)}</h1><p class="article-excerpt">${esc(c.work)}</p><img class="article-image" src="${p.image}" width="960" height="600" alt="Aperçu du projet ${esc(c.project)}" fetchpriority="high"><div class="prose"><h2>Le besoin</h2><p>${esc(c.need)}</p><h2>Le travail réalisé</h2><p>${esc(c.work)}</p>${c.sections.map(([h,text])=>`<h2>${esc(h)}</h2><p>${esc(text)}</p>`).join('')}<h2>Le retour du client</h2><blockquote>${esc(t.content)}</blockquote><p>${esc(t.name)}</p><p><a href="${p.link}" target="_blank" rel="noopener noreferrer">Consulter le site ${esc(c.project)} ↗</a></p><h2>Pour préparer votre projet</h2><ul><li><a href="/creation-site-web-toulouse">Création de sites web : périmètre et tarifs</a></li><li><a href="/identite-visuelle-toulouse">Création de logo et d’identité visuelle</a></li><li><a href="/blog/prix-creation-site-vitrine">Comparer les budgets d’un site vitrine</a></li></ul></div>${cta}<h2>Autres projets</h2><nav class="search-links" aria-label="Autres réalisations">${caseStudies.filter(x=>x!==c).map(x=>`<a href="/realisations/${x.slug}">${esc(x.project)}</a>`).join('')}</nav></article>`,schema:[crumbs([['Accueil','/'],['Réalisations','/realisations'],[c.project,url]]),{'@type':'CreativeWork','@id':origin+url+'#project',name:c.project,description:c.description,url:origin+url,image:origin+p.image,creator:{'@id':origin+'/#organization'},inLanguage:'fr-FR'}]});
  }
}
