import * as THREE from 'three';
import {wordmark} from './wordmark.js';
export function createScene(host,finish){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#0d0d11');scene.fog=new THREE.FogExp2('#0d0d11',.018);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;
 host.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
 const camera=new THREE.PerspectiveCamera(42,1,.1,150);const group=new THREE.Group();scene.add(group);
 const outline=new THREE.ShapePath();let omit=false;for(const c of wordmark){if(c.type==='M')omit=c.x>16;if(omit)continue;switch(c.type){case'M':outline.moveTo(c.x,-c.y);break;case'L':outline.lineTo(c.x,-c.y);break;case'Q':outline.quadraticCurveTo(c.x1,-c.y1,c.x,-c.y);break;case'C':outline.bezierCurveTo(c.x1,-c.y1,c.x2,-c.y2,c.x,-c.y);break;case'Z':outline.currentPath.closePath();break}}
 const geometry=new THREE.ExtrudeGeometry(outline.toShapes(),{depth:.55,bevelEnabled:true,bevelThickness:.07,bevelSize:.05,bevelSegments:3,curveSegments:12});
 const face=new THREE.MeshPhysicalMaterial({color:'#ccb9ff',metalness:.6,roughness:.23,clearcoat:1,clearcoatRoughness:.15});const side=new THREE.MeshStandardMaterial({color:'#6b43bd',metalness:.8,roughness:.28});const logo=new THREE.Mesh(geometry,[face,side]);logo.position.set(-9,-1.6,0);group.add(logo);
 const plus=new THREE.Shape();const points=[[-.3,1.3],[.3,1.3],[.3,.3],[1.3,.3],[1.3,-.3],[.3,-.3],[.3,-1.3],[-.3,-1.3],[-.3,-.3],[-1.3,-.3],[-1.3,.3],[-.3,.3]];points.forEach(([x,y],i)=>i?plus.lineTo(x,y):plus.moveTo(x,y));plus.closePath();const plusGeo=new THREE.ExtrudeGeometry(plus,{depth:.65,bevelEnabled:true,bevelThickness:.08,bevelSize:.08,bevelSegments:4});const plusMat=new THREE.MeshStandardMaterial({color:'#dceba6',emissive:'#a5b67c',emissiveIntensity:.25,metalness:.6,roughness:.22});const plusMesh=new THREE.Mesh(plusGeo,plusMat);plusMesh.position.set(9.1,-.12,.1);group.add(plusMesh);
 scene.add(new THREE.AmbientLight('#b8a0ef',2));const key=new THREE.DirectionalLight('#e6d7ff',5);key.position.set(-6,8,12);scene.add(key);const rim=new THREE.PointLight('#9770ff',180,60);rim.position.set(7,3,5);scene.add(rim);const fill=new THREE.DirectionalLight('#dceba6',2);fill.position.set(10,-2,5);scene.add(fill);
 const grid=new THREE.GridHelper(100,70,'#69508d','#292036');grid.position.y=-5;grid.position.z=-20;scene.add(grid);
 const rings=[];for(let i=0;i<3;i++){const g=new THREE.TorusGeometry(11+i*3,.014,4,120),m=new THREE.MeshBasicMaterial({color:'#8061b0',transparent:true,opacity:.25-i*.05});const ring=new THREE.Mesh(g,m);ring.position.z=-7-i*2;ring.rotation.x=.35+i*.1;scene.add(ring);rings.push(ring)}
 const positions=new Float32Array(240*3);for(let i=0;i<positions.length;i+=3){positions[i]=(Math.random()-.5)*65;positions[i+1]=(Math.random()-.5)*30;positions[i+2]=-Math.random()*60}const starsGeo=new THREE.BufferGeometry();starsGeo.setAttribute('position',new THREE.BufferAttribute(positions,3));const stars=new THREE.Points(starsGeo,new THREE.PointsMaterial({color:'#bda8f7',size:.05,transparent:true,opacity:.6}));scene.add(stars);
 let target=32;const resize=()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();target=Math.max(27,24/(2*Math.tan(THREE.MathUtils.degToRad(21))*camera.aspect))};resize();window.addEventListener('resize',resize);let frame=0;const start=performance.now();let disposed=false;
 function tick(now){if(disposed)return;const t=(now-start)/1000,e=1-Math.pow(1-Math.min(t/2.4,1),3);camera.position.set(Math.sin(t*.4)*.4,.35,target+12*(1-e));camera.lookAt(0,0,0);group.rotation.y=-.55*(1-e)+Math.sin(t*.5)*.045;group.rotation.x=.12*(1-e);group.position.y=Math.sin(t*.8)*.12;plusMesh.rotation.y=(1-e)*Math.PI*1.5;grid.position.z=-20+(t*3)%1.43;rings.forEach((r,i)=>{r.rotation.z=t*(i%2?.06:-.05)});stars.rotation.z=t*.007;renderer.render(scene,camera);host.classList.add('intro-ready');frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);
 renderer.domElement.addEventListener('webglcontextlost',finish,{once:true});
 return()=>{disposed=true;cancelAnimationFrame(frame);window.removeEventListener('resize',resize);scene.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()});renderer.dispose()};
}
