import fs from 'node:fs/promises';
import path from 'node:path';
import {esc,data} from './templates.mjs';
const origin='https://rosevaldesign.com';
const organization={'@id':origin+'/#organization'};
const tools=[
 {slug:'generateur-identite-visuelle',route:'brand',name:'Générateur d’identité visuelle',title:'Générateur de Brand Kit gratuit | Roseval +',description:'Créez un Brand Kit : couleurs, typographies, logo typographique et charte visuelle. Personnalisez votre identité et exportez vos fichiers avec Roseval +.',summary:'Le Brand Kit Generator de Roseval + permet de composer une identité visuelle à partir du nom de votre marque, de ses couleurs et de ses typographies, directement dans votre navigateur.',steps:['Renseignez le nom, la signature et le secteur de votre marque.','Choisissez une palette et une typographie, ou extrayez les couleurs d’une image.','Ajustez votre identité, puis exportez votre charte ou votre logo typographique.'],details:[['Un point de départ pour votre marque','L’outil associe les couleurs, les caractères et les déclinaisons de votre nom. Vous pouvez enregistrer plusieurs identités dans votre espace local et les réutiliser dans les générateurs de carrousels et de mockups.'],['Des fichiers à réutiliser','Exportez le logo en SVG ou PNG, le monogramme en PNG et la charte à imprimer en PDF. Le logo généré est une composition typographique personnalisable ; pour une création de symbole originale et un accompagnement, le studio propose une prestation d’identité visuelle.']],faq:[['Puis-je utiliser mes propres couleurs ?','Oui. Vous pouvez personnaliser la couleur principale et extraire une palette depuis une image importée.'],['Le Brand Kit est-il enregistré en ligne ?','Non. Les identités sont enregistrées dans le navigateur utilisé. Conservez aussi une sauvegarde exportée pour ne pas dépendre du stockage de cet appareil.']]},
 {slug:'generateur-carrousel',route:'carousel',name:'Générateur de carrousels',title:'Générateur de carrousels gratuit, 22 designs | Roseval +',description:'Créez des carrousels de 3 à 10 slides avec 22 designs, vos textes et vos photos. Formats carré, portrait, story et paysage, exports PNG et SVG.',summary:'Le Carousel Generator de Roseval + transforme un sujet en une trame de 3 à 10 slides à personnaliser. Il propose 22 directions artistiques et quatre formats : carré, portrait, story et paysage.',steps:['Indiquez le sujet, le nombre de slides, le format et l’angle éditorial.','Choisissez un design et adaptez chaque titre, texte et image à votre message.','Prévisualisez les slides, puis exportez les visuels ou le carrousel en ZIP.'],details:[['Gardez la main sur votre contenu','Les trames sont générées localement et doivent être adaptées à votre activité. Ajoutez vos photos slide par slide, changez leur cadrage et réorganisez les pages. Régénérer une trame remplace les textes et les images du carrousel actuel.'],['Une identité cohérente dans chaque format','Le carrousel utilise la palette et les typographies de votre Brand Kit. Exportez les slides en PNG ou SVG, une planche de présentation, ou utilisez l’impression pour créer un PDF. L’outil prépare les fichiers ; il ne publie pas sur vos réseaux sociaux.']],faq:[['Combien de slides puis-je créer ?','Un carrousel contient de 3 à 10 slides. Vous pouvez ajouter, dupliquer, déplacer et supprimer des slides dans cette limite.'],['Puis-je ajouter mes photos ?','Oui, chaque slide accepte une image JPG, PNG ou WebP de 5 Mo maximum. Les images sont traitées dans votre navigateur.']]},
 {slug:'generateur-mockup',route:'mockup',name:'Générateur de mockups',title:'Générateur de mockups de marque gratuit | Roseval +',description:'Prévisualisez votre identité sur différents supports avec Roseval +. Importez votre visuel, ajustez l’ambiance, la rotation et l’échelle, puis exportez.',summary:'Le Mockup Generator de Roseval + met en situation votre identité sur des supports graphiques. Il sert à présenter une idée de marque, une composition ou un visuel avant sa production.',steps:['Choisissez un support et l’identité de marque à présenter.','Importez votre visuel ou utilisez votre marque, puis réglez le texte et l’ambiance.','Ajustez la rotation et l’échelle, vérifiez le rendu et exportez la présentation.'],details:[['Des supports pour présenter une intention','Explorez notamment la carte de visite, le t-shirt, l’ordinateur ou le vinyle. Les rendus sont des représentations graphiques personnalisables, destinées à comparer et à présenter vos choix visuels.'],['Du concept à la présentation','Choisissez une ambiance studio, sombre, colorée ou transparente. Ces mockups ne remplacent pas un gabarit d’impression ni un bon à tirer : les dimensions et contraintes de fabrication restent à confirmer avec votre prestataire.']],faq:[['Puis-je importer mon propre visuel ?','Oui. Le générateur permet d’importer une image et de la présenter sur le support choisi.'],['Le mockup est-il un fichier prêt à imprimer ?','Non. C’est un visuel de présentation. Le fichier de production doit respecter les spécifications de l’imprimeur ou du fabricant.']]},
 {slug:'kit-lancement-entreprise',route:'launch',name:'Kit de lancement d’entreprise',title:'Business Launch : kit de lancement de marque | Roseval +',description:'Préparez votre lancement avec Roseval + : offre, public, objectifs, identité et supports de communication réunis dans un parcours à personnaliser.',summary:'Le Business Launch Generator de Roseval + aide à structurer le lancement d’une offre : public visé, objectif, prix, date et actions à préparer. Il réunit les outils créatifs dans un parcours de travail.',steps:['Décrivez votre offre, votre public et l’objectif de votre lancement.','Précisez le prix et la date envisagée, puis adaptez les éléments proposés.','Préparez vos supports de marque et suivez les actions de votre checklist.'],details:[['Clarifier avant de communiquer','Le parcours vous invite à formuler une offre et à choisir les messages utiles à votre public. Les suggestions constituent une base de travail : adaptez-les à vos prestations, à vos conditions et aux informations que vous pouvez justifier.'],['Relier les supports de votre lancement','Utilisez le Brand Kit pour l’identité, le générateur de carrousels pour vos contenus et les mockups pour présenter votre marque. Exportez vos éléments et sauvegardez votre projet sur votre appareil.']],faq:[['L’outil crée-t-il juridiquement mon entreprise ?','Non. Il aide à préparer l’offre et la communication. Il ne réalise pas les formalités administratives et ne remplace pas un conseil adapté à votre situation.'],['Ai-je besoin d’un compte ?','Les outils actuels s’utilisent sans inscription. Les projets restent enregistrés dans le navigateur et peuvent être sauvegardés par export.']]}
];
const services=[
 {url:'/creation-site-web-toulouse',name:'Création de sites web à Toulouse',title:'Création de site web à Toulouse dès 399 € HT | Roseval',description:'Freelance web à Toulouse : sites vitrines pour artisans et petites entreprises, design adapté, affichage mobile et bases SEO. Projet sur devis dès 399 € HT.',summary:'Roseval Design est le studio indépendant d’Antonny Freval Ros à Toulouse. Il conçoit des sites web pour présenter le savoir-faire des artisans et petites entreprises et faciliter les demandes de contact.',details:[['Quel budget prévoir pour un site vitrine ?','Le projet sur mesure débute à 399 € HT, avec un périmètre défini au devis. La formule simple démarre à 39 € HT par mois pour 3 à 5 pages, avec un engagement minimum de 12 mois, soit 468 € HT au tarif de départ. Ces deux formules répondent à des besoins différents.'],['Que précise le devis ?','Le nombre de pages, les contenus, les fonctionnalités, les retours inclus, l’hébergement et le nom de domaine sont précisés avant le démarrage. Les accès remis à la livraison et les conditions de maintenance sont également définis ; ils ne sont pas présumés inclus dans le prix de départ.'],['Comment se déroule le projet ?','L’échange initial sert à comprendre votre activité et vos objectifs. Viennent ensuite la conception, l’intégration, les tests et la mise en ligne après validation. Le délai indicatif d’un site vitrine standard est de 2 à 3 semaines, à confirmer selon les contenus et le périmètre.']]},
 {url:'/referencement-local-toulouse',name:'Référencement local à Toulouse',title:'SEO local à Toulouse pour artisans et TPE | Roseval Design',description:'Améliorez la visibilité de votre activité à Toulouse : audit SEO, contenu des pages, structure technique et référencement local avec Roseval Design.',summary:'Roseval Design accompagne les artisans et petites entreprises de Toulouse dans l’amélioration de leur visibilité sur le web. Le travail SEO relie les besoins de vos clients, le contenu de votre site et sa qualité technique.',details:[['Un audit avant les optimisations','L’analyse porte sur les pages importantes, les intentions de recherche, les titres, les descriptions, les liens internes et les points techniques qui peuvent gêner l’exploration. Elle permet de prioriser les corrections utiles à votre activité.'],['Un contenu local précis','Présentez clairement vos services, votre zone d’intervention et vos réalisations. Les informations de votre site et de vos profils professionnels doivent être cohérentes. La démarche privilégie des pages utiles à vos visiteurs, sans multiplier des pages de villes identiques.'],['SEO et moteurs de réponse IA','Des explications claires, des pages accessibles et des données structurées fidèles au contenu aident les moteurs à comprendre une activité. Ni une position sur Google ni une citation dans une réponse IA ne peuvent être garanties. Les progrès se suivent dans la durée.']]},
 {url:'/identite-visuelle-toulouse',name:'Identité visuelle à Toulouse',title:'Logo et identité visuelle à Toulouse | Roseval Design',description:'Créez une identité cohérente avec Roseval Design à Toulouse : logo, couleurs, charte et supports de communication. Pack image de marque dès 199 € HT.',summary:'Roseval Design accompagne la création d’identités visuelles pour les indépendants, artisans et petites entreprises. Le travail porte sur le logo, les couleurs, la typographie et leur déclinaison sur vos supports.',details:[['Une identité adaptée à votre activité','Le point de départ est votre métier, votre clientèle et la manière dont vous souhaitez présenter votre entreprise. Ces éléments orientent les propositions et les choix graphiques.'],['Quels supports préparer ?','Le pack image de marque est présenté à partir de 199 € HT. Logo, charte graphique, cartes de visite et supports marketing font partie des besoins à préciser ensemble. Le devis fixe les livrables, les variantes, les retours et les droits remis.'],['Accompagnement ou création autonome ?','Le studio s’adresse aux projets qui demandent un échange et une création accompagnée. Roseval + permet d’explorer une palette, une typographie et un logo typographique en autonomie. Roseval Kits sert à décliner vos contenus sur les réseaux sociaux.']]}
];
const links=()=>`<nav aria-label="Services et outils Roseval" class="search-links"><a href="/creation-site-web-toulouse">Création de sites web</a><a href="/referencement-local-toulouse">SEO local</a><a href="/identite-visuelle-toulouse">Identité visuelle</a><a href="/outils">Tous les outils créatifs</a></nav>`;
const css=`<style>.search-content{max-width:1100px;margin:60px auto;padding:32px 24px;line-height:1.75}.search-content h1{font-size:clamp(2rem,5vw,4rem);line-height:1.12;max-width:950px}.search-content h2{font-size:clamp(1.35rem,3vw,2rem);line-height:1.3;margin:30px 0 12px}.search-content p{max-width:850px}.search-content .search-lead{font-size:1.18rem;color:inherit;opacity:.88}.search-links{display:flex;flex-wrap:wrap;gap:14px 24px;margin:28px 0}.search-links a,.search-content a:not(.button){color:inherit;text-decoration:underline;text-underline-offset:5px}.search-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:20px;margin:24px 0}.search-card{padding:24px;border:1px solid #8885;border-radius:18px}.search-card h2{margin-top:0}.search-content li{margin:10px 0}.search-content .button{margin:18px 12px 18px 0}.search-note{font-size:.9rem;opacity:.75}</style>`;
const breadcrumb=(name,url)=>({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Accueil',item:origin+'/'},{'@type':'ListItem',position:2,name,item:origin+url}]});
const sections=items=>items.map(([h,p])=>`<section><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('');
export async function buildSearchPages(write){
 for(const s of services)await write(s.url,{title:s.title,description:s.description,body:`${css}<article class="search-content"><a href="/web">← Le studio Roseval</a><p class="eyebrow">STUDIO INDÉPENDANT · TOULOUSE</p><h1>${esc(s.name)}</h1><p class="search-lead">${esc(s.summary)}</p>${sections(s.details)}<p>Basé à Toulouse, le studio accompagne en priorité les projets en Haute-Garonne et en Occitanie. Les échanges et le travail peuvent se faire à distance.</p><a class="button primary" href="/web#contact">Présenter mon projet ↗</a><a class="button" href="/web#portfolio">Voir les réalisations ↗</a>${links()}<p class="search-note">Par Antonny Freval Ros · Roseval Design</p></article>`,schema:[breadcrumb(s.name,s.url),{'@type':'Service','@id':origin+s.url+'#service',name:s.name,description:s.summary,provider:organization,areaServed:['Toulouse','Haute-Garonne','Occitanie'],url:origin+s.url}]});
 for(const t of tools){const url='/outils/'+t.slug;await write(url,{title:t.title,description:t.description,body:`${css}<article class="search-content"><a href="/outils">← Les outils créatifs</a><p class="eyebrow">ROSEVAL + · OUTIL EN LIGNE</p><h1>${esc(t.name)}</h1><p class="search-lead">${esc(t.summary)}</p><a class="button primary" href="/roseval-plus#${t.route}">Ouvrir le générateur ↗</a><h2>Comment l’utiliser ?</h2><ol>${t.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${sections(t.details)}<h2>Questions fréquentes</h2>${t.faq.map(([q,a])=>`<section><h3>${esc(q)}</h3><p>${esc(a)}</p></section>`).join('')}<p class="search-note">Version actuelle gratuite, sans inscription. Les créations restent sur cet appareil : exportez une sauvegarde pour les conserver. JavaScript est nécessaire pour utiliser le générateur.</p><nav class="search-links" aria-label="Outils complémentaires">${tools.filter(x=>x!==t).map(x=>`<a href="/outils/${x.slug}">${esc(x.name)}</a>`).join('')}<a href="/kits">Modèles de publications pour artisans</a></nav></article>`,schema:[breadcrumb(t.name,url),{'@type':'WebApplication','@id':origin+url+'#application',name:t.name,description:t.summary,url:origin+url,applicationCategory:'DesignApplication',operatingSystem:'Navigateur web',browserRequirements:'JavaScript activé',inLanguage:'fr-FR',isAccessibleForFree:true,creator:organization,featureList:t.steps}]})}
 await write('/outils',{title:'Outils créatifs gratuits : Brand Kit, carrousel, mockup | Roseval',description:'Découvrez les outils Roseval + et Roseval Kits : identité visuelle, carrousels, mockups, lancement de marque et modèles de publications pour artisans.',body:`${css}<section class="search-content"><p class="eyebrow">LE STUDIO CRÉATIF EN AUTONOMIE</p><h1>Des outils pour créer votre marque et vos contenus.</h1><p class="search-lead">Roseval + réunit des générateurs personnalisables pour votre identité et vos supports. Roseval Kits propose des modèles de publications adaptés aux métiers de l’artisanat. Leur version actuelle est gratuite et ne demande pas de compte.</p><div class="search-grid">${tools.map(t=>`<article class="search-card"><h2>${esc(t.name)}</h2><p>${esc(t.summary)}</p><a href="/outils/${t.slug}">Découvrir le fonctionnement ↗</a></article>`).join('')}<article class="search-card"><h2>Roseval Kits</h2><p>30 directions créatives, 8 palettes et 6 formats pour personnaliser les publications des cuisinistes, menuisiers et professionnels de la rénovation.</p><a href="/kits">Explorer les packs ↗</a></article></div><h2>Quel univers choisir ?</h2><p>Choisissez Kits pour partir d’un sujet métier et de vos photos de réalisations. Choisissez Roseval + pour construire une identité et des supports coordonnés. Pour un site ou une identité accompagnée, adressez-vous au studio Roseval.</p>${links()}</section>`,schema:[breadcrumb('Outils créatifs','/outils')]});
}
export async function enhanceSearch(urls){
 for(const url of urls){const file=url==='/kits/atelier'?'dist/kits/atelier.html':path.join('dist',url,'index.html');let html=await fs.readFile(file,'utf8');
  if(url==='/')html=html.replaceAll('Trois univers, une même signature','Création web à Toulouse & outils créatifs');
  if(url==='/web')html=html.replaceAll('Agence web à Toulouse, création de sites & SEO','Freelance web à Toulouse, sites & SEO');
  const title=html.match(/<title>(.*?)<\/title>/s)?.[1]||'Roseval Design',description=html.match(/<meta name="description" content="([^"]*)"/)?.[1]||'';
  const post=data.posts.find(p=>url==='/blog/'+p.slug);
  const shareImage=post?new URL(post.image,origin).href:origin+'/og-image.jpg';
  if(post)html=html.replace(/<meta property="og:image" content="[^"]*">/,`<meta property="og:image" content="${shareImage}">`);
  let extra='';const meta=(key,value,property=false)=>{if(!html.includes(`${property?'property':'name'}="${key}"`))extra+=`<meta ${property?'property':'name'}="${key}" content="${value}">`};
  meta('robots','index, follow, max-image-preview:large');for(const [key,value]of Object.entries({'og:title':title,'og:description':description,'og:url':origin+url,'og:type':'website','og:site_name':'Roseval Design','og:locale':'fr_FR','og:image':shareImage,'og:image:alt':post?esc(post.title):'Roseval Design — studio web et outils créatifs'}))meta(key,value,true);
  meta('twitter:card','summary_large_image');meta('twitter:title',title);meta('twitter:description',description);meta('twitter:image',shareImage);if(post){meta('article:published_time',post.date,true);meta('article:author',origin+'/web#about',true);}
  const graph=[{'@type':'WebPage','@id':origin+url+'#webpage',url:origin+url,name:title.replaceAll('&amp;','&'),description:description.replaceAll('&amp;','&'),inLanguage:'fr-FR',isPartOf:{'@id':origin+'/#website'},about:organization}];
  if(['/kits','/kits/atelier','/roseval-plus'].includes(url)){graph.push({'@type':'Organization',...organization,name:'Roseval Design',url:origin+'/'},{'@type':'WebSite','@id':origin+'/#website',name:'Roseval Design',url:origin+'/',inLanguage:'fr-FR'},breadcrumb(title.replaceAll('&amp;','&'),url));}
  extra+=`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c')}</script>`;
  html=html.replace('</head>',extra+'</head>');
  if(url==='/roseval-plus')html=html.replace('</main>',`</main>${css}<section class="search-content" aria-labelledby="tools-guide"><h2 id="tools-guide">Les outils Roseval +, en détail</h2><p>Créez une identité, des carrousels, des mockups et un kit de lancement dans votre navigateur. Découvrez les possibilités et les étapes de chaque outil.</p><nav class="search-links" aria-label="Guides des générateurs">${tools.map(t=>`<a href="/outils/${t.slug}">${esc(t.name)}</a>`).join('')}</nav><p class="search-note">Sans inscription · Créations enregistrées sur cet appareil · Sauvegarde par export</p></section>`);
  else if(url==='/kits')html=html.replace('</main>',`${css}<section class="search-content"><h2>Des publications adaptées à votre métier</h2><p>Roseval Kits propose 30 directions créatives, 8 palettes et 6 formats pour les cuisinistes, menuisiers et professionnels de la rénovation. Importez vos photos, personnalisez les textes et exportez vos visuels en PNG. Les packs de démonstration sont gratuits et utilisables hors ligne.</p><h2>Quelle différence avec Roseval + ?</h2><p>Kits part de sujets métier et de photos de réalisations. Roseval + réunit la création d’identité, les carrousels et les mockups pour coordonner votre communication.</p><a href="/outils">Découvrir les générateurs Roseval + ↗</a></section></main>`);
  else if(url!=='/kits/atelier')html=html.replace('</main>',`${css}<div class="search-content">${links()}</div></main>`);
  await fs.writeFile(file,html);
 }
 // The animation is embedded in the homepage; it is not a separate search destination.
 const intro='dist/intro.html';let html=await fs.readFile(intro,'utf8');if(!html.includes('name="robots"'))html=html.replace('</head>','<meta name="robots" content="noindex, follow"></head>');await fs.writeFile(intro,html);
}
